# Helm config
mixer:
  gcpProjectID: datcom-mixer-autopush
  serviceName: autopush.api.datacommons.org

ingress:
  name: mixer-ingress-autopush
  annotations:
    {
      ingress.gcp.kubernetes.io/pre-shared-cert: "mixer-certificate,multi-domain-2022",
    }

serviceGroups:
  - mixer-svg-service:
      urlPaths:
        - "/place/stat-var-group/*"
        - "/stat-var/*"
        - "/v1/info/variable/group/*"
        - "/v1/variable/*"
      replicas:
        default: 2
        min: 2
        max: 8
      resources:
        memoryRequest: "8G"
        memoryLimit: "8G"
  - recon:
      urlPaths:
        - "/v1/recon/*"
      replicas:
        default: 4
        min: 4
        max: 8
      resources:
        memoryRequest: "3G"
        memoryLimit: "3G"
  - mixer-default-service:
      urlPaths:
        - "/*"
      replicas:
        default: 15
        min: 15
        max: 30
      resources:
        memoryRequest: "3G"
        memoryLimit: "3G"

# GCP level config
ip: 34.117.145.125
region: us-central1
api_title: DataCommons API (Autopush)
api:
  - datacommons.Mixer
  - datacommons.Recon
nodes: 4
