# Helm config
mixer:
  hostProject: datcom-mixer
  serviceName: api.datacommons.org

ingress:
  enabled: true
  name: mixer-ingress-prod
  annotations:
    {
      ingress.gcp.kubernetes.io/pre-shared-cert: "mixer-certificate,multi-domain-2022",
    }

serviceGroups:
  svg:
    replicas: 10
  recon:
    replicas: 80
  observation:
    replicas: 20
  default:
    replicas: 40

# GCP level config
ip: 35.244.133.155
region: us-central1
api_title: DataCommons API
nodes: 6
