apiVersion: v1
kind: Namespace
metadata:
  name: mixer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mixer-ksa-dev
  namespace: mixer
---
apiVersion: v1
data:
  projectId: datcom-website-dev
  serviceName: mixer.endpoints.datcom-website-dev.cloud.goog
kind: ConfigMap
metadata:
  name: mixer-configmap-dev
  namespace: mixer
---
apiVersion: v1
data:
  bigquery.version: google.com:datcom-store-dev.dc_kg_2020_12_17_09_33_15
  bigtable.version: borgcron_2020_12_17_09_33_15
kind: ConfigMap
metadata:
  name: store-configmap-dev-6f7f9fmmck
  namespace: mixer
---
apiVersion: v1
data:
  service-account-key.json: |
    ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiZGF0Y2
    9tLXdlYnNpdGUtZGV2IiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiNWIzZTYxYzNhNDY1YmU2
    NzRjOWQwMjZkNmY0ZTQ0MmEwNWRmZmNkNSIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQk
    VHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZ3SUJBREFOQmdrcWhraUc5dzBCQVFFRkFB
    U0NCS2t3Z2dTbEFnRUFBb0lCQVFEQUoyV0FtWG1PUEpMNVxuR1VFb3BydVVuL2JudDZDR3
    JiUVRyZ0hQZERkRHpPbE1YNGhqNy9QL3NvYU00cGZka04vRXVRSURTVkFJdW5tMVxuVm80
    LzVBdlpteDJZaTVOQnJ0NXZ0THRrcDB5ejA4eU4yMEwyUkhUYXk2eFR3WlpsMzBqcjM4aG
    94dkswQzJjVlxuTWIzSkFTK1FoaU1wM2hhbkZrdkszNlV4di9sUFV4L3IwSCtMMkxlZytN
    UlJGaDVXTHhJZlRzUlVBd2liVVhpQVxuQk9RbFhuTFQ0c2ZvK1pIOFoyTXY2aGw2bkJ4cn
    BCTnhKZWpJNm1SVE5mQ3U1NzdWRjY0MnEwSjI5cWJjQzZVTFxubXZ2TWtuN2tKVjNlVUE5
    ajRNQ0kxZ0Z5V3hlMXhpMlF4MlNXdk80WitkWkY4SXptZmhrRWhHdXI3bW4zRlZ0VFxudV
    F5cTlGZnpBZ01CQUFFQ2dnRUFHNTlPTXc5Yzd2cDhNanpVSmhEWjFFS3VqcDdSLzZwR3di
    RjQ1eWFRcnpsc1xuckNMcmkxbzZIQjdBd3Mzc0FOakxvZzdxWUNpUXpjQm9zSTJ4d3pONE
    ZKNzh3U29IVUNEZ0x2U3ZINGdCT2JTUFxucWpERHpuMEd3MUVXQTdCSGUzdCtreEhIVUhD
    UkFSckdoY0J4eE14YjF3M0JUa3B6dlM4eVZBYVVTN09LRmtIZ1xuQm5iVXVCSDAvVmlseW
    R6L1k3QWtlRThvQW16YUl2SHV1bmhZRHN4cVRtVlVxdk9GN2dKZ1FBOTJabWtYTTRvbFxu
    R3NYcDB6NmhhRzFkclQ2SWVmblVUWFRuNHZZTFBBbGgyT3ZybUlUK0JCcDZzS01aZDFWTk
    lCZVNPVUprci9Qb1xuQ1hGRzY5d3hwSEx0c2xqV3RVRGZ1ellNSzQ0Z3NZWmlTd2FlWWNs
    RWdRS0JnUURnZmM5TlYrbHZxcUg3U2xTa1xuK0cxeHMvZDh1b1BFelYwM0w0TlJNK2tuUW
    pvVSt6SXJDNEFwby9CMXltblhTMkd3N21HUCtCeGhBYzIxRzdIK1xuQ1lTMkk5SU5pYUdM
    UGVIdU9QQlZvK0U2aktHTEc3SnFSdXRnbW52S0k4TktBSjNsbTcxSUxweVAwWHhMU3o3ZV
    xuUGtHT0FQZlpNbS96NzRzN3RoZExwQWp0UVFLQmdRRGJINnI0V29DaE1QWTFJcDArd3d0
    S0ROZWNWbUg3NGRmWFxuT0FWZ3BEZjlRclFBVm9ibFZrQmZtdEhSWmJOdmVOeTJPK3owYn
    R3U0xpUnVzdHg0Rjd1TzlacXk0UTFQaEViMFxuc0RlVlJibUtUNE0wTTEwYkFhZldOTFpo
    SWFHclBoRlI1S1U3MEwyYlV2MndPZmRhYXRZTHJXTnkxQlR3c3dkQ1xuKy9ybURhUVVNd0
    tCZ1FDNjJYeDJEN29JYTZtdkVzc3BGRzFqdWpzLzRhNVRXK3MrUjVteE9OZlRDVmgycGky
    M1xuampiNmNhMXZIUzdETjhiMEVUVzdNdlBMK2toUmVkL0laZnZEN2tTalorN0JpcHhHUD
    dZcVVlRGhiclAycVBMelxuYWx2M2FCMm92ZU9KOE1GN253a0l6Mk1ZZ1hCRzZ6WkVuT1RM
    WVJycCtRVWRzRC9mVDB4TWRSZkpBUUtCZ1FDaVxuTW5POHVFa2toL2lIWm1MYzlVVWpBQl
    NOVGNmanljMmFLb2FZZlpaUUtwTFErVHVMQU9oUG5Hc1pROTJwY3Q1MVxuS2pDQTBwcWwv
    bS9MWFN3aTNQWmhvTjFzOFhlSDE1TXFSbEl1ZFZrY3p6U0FiRkRMejlMcmxVTTI3TTBkMD
    ZqQVxuWks0R2M4SVYrajE4dDd1bnV4Tkx1NEcwbXRZUlFZUHJpbGV5K0gvdXp3S0JnUUMy
    SnB6aVZpSHBhUXdCOUdTdFxud3p2b0k3THgxTDhSbUZQYWxubWptTVpKQnh2NG0zVFZ1Wn
    RRc1ZLUmZCMWovdXBSd2lwSi8wb0luL3JLT0N4YlxueDhnc0kybldjTFFOYk95L2RHcjlm
    TTArMTJhR0g2SitEUkU0aUxETjlKb1pKSWNEUytZQlB3dE9KTnF3cDQweFxubzNYNDVVaG
    krN0dnOFFHZzZ1VkI4Rms0U1E9PVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwK
    ICAiY2xpZW50X2VtYWlsIjogIm1peGVyLXJvYm90QGRhdGNvbS13ZWJzaXRlLWRldi5pYW
    0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMDkyODE3ODMzMjg3
    MDM0NzYxNjIiLAogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb2
    0vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29n
    bGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6IC
    JodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGll
    bnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC
    92MS9tZXRhZGF0YS94NTA5L21peGVyLXJvYm90JTQwZGF0Y29tLXdlYnNpdGUtZGV2Lmlh
    bS5nc2VydmljZWFjY291bnQuY29tIgp9Cg==
kind: Secret
metadata:
  name: service-account-key-dev
  namespace: mixer
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: mixer-service-dev
  namespace: mixer
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: mixer-grpc
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mixer-grpc-dev
  namespace: mixer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mixer-grpc
  template:
    metadata:
      labels:
        app: mixer-grpc
    spec:
      containers:
      - args:
        - --bq_dataset
        - $(BIG_QUERY)
        - --bt_table
        - $(BIG_TABLE)
        - --bt_project
        - google.com:datcom-store-dev
        - --bt_instance
        - prophet-cache
        - --project_id
        - $(PROJECT_ID)
        env:
        - name: PROJECT_ID
          valueFrom:
            configMapKeyRef:
              key: projectId
              name: mixer-configmap-dev
        - name: BIG_QUERY
          valueFrom:
            configMapKeyRef:
              key: bigquery.version
              name: store-configmap-dev-6f7f9fmmck
        - name: BIG_TABLE
          valueFrom:
            configMapKeyRef:
              key: bigtable.version
              name: store-configmap-dev-6f7f9fmmck
        image: mixer/mixer
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:12345
          initialDelaySeconds: 10
          periodSeconds: 5
        name: mixer
        ports:
        - containerPort: 12345
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:12345
          periodSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 2G
      - args:
        - --service_account_key
        - /var/secrets/google/service-account-key.json
        - --non_gcp
        - --service
        - $(SERVICE_NAME)
        - --http_port
        - "8081"
        - --backend
        - grpc://127.0.0.1:12345
        - --cors_preset
        - basic
        - --rollout_strategy
        - managed
        - --healthz
        - healthz
        env:
        - name: SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              key: serviceName
              name: mixer-configmap-dev
        image: gcr.io/endpoints-release/endpoints-runtime:1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
        name: esp
        ports:
        - containerPort: 8081
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8081
          periodSeconds: 5
        resources:
          limits:
            cpu: 100m
            memory: 1G
        volumeMounts:
        - mountPath: /var/secrets/google
          name: secret-volume
          readOnly: true
      serviceAccountName: mixer-ksa-dev
      volumes:
      - name: secret-volume
        secret:
          secretName: service-account-key-dev
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.global-static-ip-name: mixer-ip
    networking.gke.io/managed-certificates: mixer-certificate
  name: mixer-ingress-dev
  namespace: mixer
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: mixer-service-dev
          servicePort: 80
        path: /*
